// Curated support resources for transgender, nonbinary, and questioning people,
// organized country -> state/province/nation (subregion) -> city. Per the Project
// Blossom spec these are informational only, never replace professional advice,
// always show what they apply to and a last-reviewed date, and link to the
// original source. NOT an external directory API by design - avoids drift,
// tracking, or unreviewed info creeping in.
//
// IMPORTANT: this list has NOT been fully reviewed by Ellie. It is real,
// sourced research (each entry links where it came from) but treat the
// last-reviewed dates as placeholders until she confirms them, especially
// the legal-context notes for US states, which change fast. A handful of
// states came back with no named community org in this research pass and
// are deliberately left with only national-level fallback resources rather
// than shipping something invented.
//
// As of the staff resource-management build, Supabase's region_resources /
// legal_context_notes tables are the real source of truth - staff edit
// those via /admin/resources. The arrays in this file are only the
// bundled fallback for a device that's never had network access.

import { db } from "./db";
import { createClient } from "./supabase/client";

export type ResourceCategory =
  | "emergency"
  | "crisis"
  | "peer"
  | "legal"
  | "housing"
  | "general";

export interface RegionResource {
  id: string;
  country: string;
  subregion: string | null;
  cityName: string | null;
  orgName: string;
  category: ResourceCategory;
  contactInfo: string;
  availability: string | null;
  lastReviewedAt: string;
  sourceUrl: string;
  note: string | null;
}

export interface LegalContextNote {
  country: string;
  subregion: string;
  note: string;
  sourceUrl: string;
  lastReviewedAt: string;
}

export const COUNTRIES = [
  "Ireland",
  "New Zealand",
  "United Kingdom",
  "Canada",
  "Australia",
  "United States",
] as const;

export type Country = (typeof COUNTRIES)[number];

export const SUBREGIONS: Partial<Record<Country, string[]>> = {
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  "Canada": ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Northwest Territories", "Nunavut", "Yukon"],
  "Australia": ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Australian Capital Territory", "Northern Territory"],
  "United States": ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"],
};

const CATEGORY_ORDER: ResourceCategory[] = [
  "crisis",
  "emergency",
  "peer",
  "legal",
  "housing",
  "general",
];

// Bundled offline/never-synced fallback - staff now edit the live copy in
// Supabase via /admin/resources. This array only matters for a device that
// has never had network access to fetch the live data (see
// syncRegionResourcesCache below), so it doesn't need to stay perfectly in
// sync with the DB - just reasonably current.
const FALLBACK_REGION_RESOURCES: RegionResource[] = [
  {
    id: "uk-samaritans",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "Samaritans",
    category: "crisis",
    contactInfo: "Call 116 123 (free, 24/7)",
    availability: "24 hours a day, every day",
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://www.samaritans.org",
    note: null,
  },
  {
    id: "uk-switchboard",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "Switchboard LGBT+ Helpline",
    category: "peer",
    contactInfo: "Call 0300 330 0630, or chat/email via their website",
    availability: "10am-10pm, every day",
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://switchboard.lgbt",
    note: null,
  },
  {
    id: "uk-mermaids",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "Mermaids",
    category: "peer",
    contactInfo: "Support for transgender, nonbinary, and gender-diverse young people and their families",
    availability: "See website for current hours",
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://mermaidsuk.org.uk",
    note: null,
  },
  {
    id: "uk-gendered-intelligence",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "Gendered Intelligence",
    category: "peer",
    contactInfo: "Trans-led community organisation, groups and support",
    availability: "See website",
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://genderedintelligence.co.uk",
    note: null,
  },
  {
    id: "uk-galop",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "Galop",
    category: "legal",
    contactInfo: "Call 0800 999 5428 - support around hate crime, abuse, and the law",
    availability: "See website for current hours",
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://galop.org.uk",
    note: null,
  },
  {
    id: "uk-shelter",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "Shelter",
    category: "housing",
    contactInfo: "Call 0808 800 4444 - free housing advice",
    availability: "8am-8pm weekdays, 9am-5pm weekends",
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://england.shelter.org.uk",
    note: null,
  },
  {
    id: "uk-nhs-gender",
    country: "United Kingdom",
    subregion: null,
    cityName: null,
    orgName: "NHS - gender dysphoria services overview",
    category: "general",
    contactInfo: "Informational only - speak to your GP about referral pathways",
    availability: null,
    lastReviewedAt: "2026-07-13",
    sourceUrl: "https://www.nhs.uk/conditions/gender-dysphoria/",
    note: null,
  },
{
    id: "ireland-teni-transgender-equality-network-ireland",
    country: "Ireland",
    subregion: null,
    cityName: null,
    orgName: "TENI (Transgender Equality Network Ireland)",
    category: "peer",
    contactInfo: "01 873 3575",
    availability: "See website",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://teni.ie/",
    note: "National trans advocacy org, maintains its own database of further supports",
  },
  {
    id: "ireland-lgbt-ireland-helpline",
    country: "Ireland",
    subregion: null,
    cityName: null,
    orgName: "LGBT Ireland Helpline",
    category: "crisis",
    contactInfo: "1800 929 539",
    availability: "See lgbt.ie for current hours",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://lgbt.ie/",
    note: "Needs contact number reconfirmed directly on lgbt.ie",
  },
  {
    id: "ireland-transgender-family-support-line-lgbt-ireland-x-teni",
    country: "Ireland",
    subregion: null,
    cityName: null,
    orgName: "Transgender Family Support Line (LGBT Ireland x TENI)",
    category: "peer",
    contactInfo: "01 907 3707",
    availability: "Sundays 6-9pm, Tuesdays 10am-12pm",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://findahelpline.com/organizations/lgbt-ireland-transgender-family-support-line",
    note: "For family members of trans/gender-nonconforming people, not the person themselves",
  },
  {
    id: "ireland-dublin-individuality-belong-to",
    country: "Ireland",
    subregion: null,
    cityName: "Dublin",
    orgName: "IndividualiTy (BeLonG To)",
    category: "peer",
    contactInfo: "01 670 6223",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.gendered.ie/support-services/",
    note: "Transgender young people's support group",
  },
  {
    id: "ireland-cork-cork-transgender-peer-support-group",
    country: "Ireland",
    subregion: null,
    cityName: "Cork",
    orgName: "Cork Transgender Peer Support Group",
    category: "peer",
    contactInfo: "See gendered.ie for current contact",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.gendered.ie/support-services/",
    note: null,
  },
  {
    id: "ireland-national-gender-service",
    country: "Ireland",
    subregion: null,
    cityName: null,
    orgName: "National Gender Service",
    category: "general",
    contactInfo: "Informational - HSE-run gender clinic pathway",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://nationalgenderserviceireland.com/",
    note: "Ireland's public gender service pathway overview",
  },
  {
    id: "new-zealand-111-emergency-services",
    country: "New Zealand",
    subregion: null,
    cityName: null,
    orgName: "111 (emergency services)",
    category: "emergency",
    contactInfo: "111",
    availability: "24/7",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://healthify.nz/support/g/gender-diversity-support",
    note: "General NZ emergency number, immediate danger only",
  },
  {
    id: "new-zealand-1737-need-to-talk",
    country: "New Zealand",
    subregion: null,
    cityName: null,
    orgName: "1737 - Need to Talk?",
    category: "crisis",
    contactInfo: "Free call or text 1737, any time",
    availability: "24/7",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.1737.org.nz/",
    note: "General national crisis/mental health line, trained counsellors",
  },
  {
    id: "new-zealand-outline-aotearoa",
    country: "New Zealand",
    subregion: null,
    cityName: null,
    orgName: "OutLine Aotearoa",
    category: "crisis",
    contactInfo: "0800 688 5463 (0800 OUTLINE); chat at outline.org.nz/chat 6-9pm",
    availability: "See website for phone hours, chat 6-9pm daily",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://outline.org.nz/",
    note: "Rainbow-community-specific support line + counselling + Auckland-based trans/non-binary peer support",
  },
  {
    id: "new-zealand-gender-minorities-aotearoa",
    country: "New Zealand",
    subregion: null,
    cityName: null,
    orgName: "Gender Minorities Aotearoa",
    category: "peer",
    contactInfo: "04 385 0611",
    availability: "See website",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://genderminorities.com/",
    note: "NZ's leading trans-led organisation, nationwide info/support for trans people and whanau",
  },
  {
    id: "new-zealand-rainbowyouth",
    country: "New Zealand",
    subregion: null,
    cityName: null,
    orgName: "RainbowYOUTH",
    category: "peer",
    contactInfo: "See ry.org.nz",
    availability: "Drop-in centres, varies by location",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://ry.org.nz/",
    note: "Youth-focused, drop-in centres in Auckland/Tauranga/Taranaki, support workers also in Wellington/Northland/Dunedin",
  },
  {
    id: "new-zealand-auckland-rainbowyouth-auckland-trans-peer-support-homelessness-support-worker",
    country: "New Zealand",
    subregion: null,
    cityName: "Auckland",
    orgName: "RainbowYOUTH Auckland - trans peer support + homelessness support worker",
    category: "housing",
    contactInfo: "See ry.org.nz",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://ry.org.nz/",
    note: "Dedicated trans peer support and a homelessness support worker specifically in Auckland",
  },
  {
    id: "united-kingdom-scotland-national-gender-identity-clinical-network-for-scotland-nhs",
    country: "United Kingdom",
    subregion: "Scotland",
    cityName: null,
    orgName: "National Gender Identity Clinical Network for Scotland (NHS)",
    category: "general",
    contactInfo: "Referral via GP; 4 NHS GICs: Glasgow Sandyford, Edinburgh Chalmers, Aberdeen Cornhill, Inverness Raigmore",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.nn.nhs.scot/ngicns/",
    note: "Current first-appointment wait time reported around 2 years, sometimes 3.5+ years.",
  },
  {
    id: "united-kingdom-scotland-scottish-trans-alliance",
    country: "United Kingdom",
    subregion: "Scotland",
    cityName: null,
    orgName: "Scottish Trans Alliance",
    category: "peer",
    contactInfo: "See scottishtrans.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.scottishtrans.org/healthcare/",
    note: "Scottish Government Equality Unit-funded, trans rights/inclusion + healthcare guidance for Scotland specifically",
  },
  {
    id: "united-kingdom-wales-welsh-gender-service-nhs-wales-cardiff-and-vale-uhb",
    country: "United Kingdom",
    subregion: "Wales",
    cityName: null,
    orgName: "Welsh Gender Service (NHS Wales, Cardiff and Vale UHB)",
    category: "general",
    contactInfo: "Referral via Welsh GP; accepts referrals 17.5+",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://gender.wales/",
    note: "Requires Welsh residency + registration with a Welsh GP; Local Gender Teams closer to home for hormone/SLT care",
  },
  {
    id: "united-kingdom-wales-umbrella-cymru",
    country: "United Kingdom",
    subregion: "Wales",
    cityName: null,
    orgName: "Umbrella Cymru",
    category: "peer",
    contactInfo: "See gender.wales",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://gender.wales/",
    note: "Commissioned by Cardiff and Vale UHB to provide psycho-social support to Welsh Gender Service patients",
  },
  {
    id: "united-kingdom-northern-ireland-the-rainbow-project",
    country: "United Kingdom",
    subregion: "Northern Ireland",
    cityName: null,
    orgName: "The Rainbow Project",
    category: "peer",
    contactInfo: "Centres in Belfast and Foyle - see rainbow-project.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.rainbow-project.org/",
    note: "Free counselling (currently an 8+ month waitlist reported); monthly trans sexual health screening at Belfast Trans Resource Centre.",
  },
  {
    id: "united-kingdom-northern-ireland-transgenderni",
    country: "United Kingdom",
    subregion: "Northern Ireland",
    cityName: null,
    orgName: "TransgenderNI",
    category: "peer",
    contactInfo: "See transgenderni.org.uk",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transgenderni.org.uk/support/",
    note: "NI-specific trans advocacy and support",
  },
  {
    id: "united-kingdom-northern-ireland-brackenburn-clinic-adults-knowing-our-identity-clinic-under-18s",
    country: "United Kingdom",
    subregion: "Northern Ireland",
    cityName: null,
    orgName: "Brackenburn Clinic (adults) / Knowing Our Identity Clinic (under-18s)",
    category: "general",
    contactInfo: "Referral via GP, Belfast HSC Trust",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://belfasttrust.hscni.net/service/brackenburn-clinic/",
    note: "Reported long waits (3-4 years) due to staffing issues",
  },
  {
    id: "united-kingdom-england-nhs-gender-identity-clinics-england",
    country: "United Kingdom",
    subregion: "England",
    cityName: null,
    orgName: "NHS Gender Identity Clinics (England)",
    category: "general",
    contactInfo: "Referral via GP; 8 GICs including London (Tavistock and Portman/North London NHS FT), Sheffield, Manchester, West of England",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.nhs.uk/nhs-services/how-to-find-an-nhs-gender-identity-clinic/",
    note: "London clinic is the oldest/largest in the UK (est. 1966)",
  },
  {
    id: "united-kingdom-england-gendered-intelligence",
    country: "United Kingdom",
    subregion: "England",
    cityName: null,
    orgName: "Gendered Intelligence",
    category: "peer",
    contactInfo: "5-day-a-week support line - see gendered.intelligence site",
    availability: "5 days/week",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://genderedintelligence.co.uk",
    note: "UK's largest trans-led charity, with a 5-day-a-week support line and youth groups.",
  },
  {
    id: "united-kingdom-england-manchester-lgbt-foundation",
    country: "United Kingdom",
    subregion: "England",
    cityName: "Manchester",
    orgName: "LGBT Foundation",
    category: "peer",
    contactInfo: "See lgbt.foundation",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://lgbt.foundation/trans-local-groups/",
    note: "National charity based in Manchester, trans-specific services + local groups directory",
  },
  {
    id: "canada-trans-lifeline-canada",
    country: "Canada",
    subregion: null,
    cityName: null,
    orgName: "Trans Lifeline Canada",
    category: "crisis",
    contactInfo: "(877) 330-6366",
    availability: "Mon-Fri 10am-6pm Pacific / 1-9pm Eastern",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://translifeline.org/contact/",
    note: "Trans-led peer support and crisis hotline. Limited hours - not 24/7.",
  },
  {
    id: "canada-egale-canada",
    country: "Canada",
    subregion: null,
    cityName: null,
    orgName: "Egale Canada",
    category: "peer",
    contactInfo: "See egale.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://egale.ca/",
    note: "Canada's leading 2SLGBTQI advocacy/research/education organisation",
  },
  {
    id: "canada-pflag-canada",
    country: "Canada",
    subregion: null,
    cityName: null,
    orgName: "PFLAG Canada",
    category: "peer",
    contactInfo: "See pflagcanada.ca, local chapters nationwide",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.pflagcanada.ca/",
    note: "Peer support/education/advocacy network with chapters across Canada",
  },
  {
    id: "canada-ontario-rainbow-health-ontario",
    country: "Canada",
    subregion: "Ontario",
    cityName: null,
    orgName: "Rainbow Health Ontario",
    category: "general",
    contactInfo: "Service Provider Directory at rainbowhealthontario.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.rainbowhealthontario.ca/",
    note: "Directory of trans-affirming providers across Ontario + trans health knowledge base",
  },
  {
    id: "canada-ontario-camh-gender-identity-clinic",
    country: "Canada",
    subregion: "Ontario",
    cityName: null,
    orgName: "CAMH Gender Identity Clinic",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.camh.ca/en/patients-and-families/programs-and-services/gender-identity-clinic-adult",
    note: "Since 2016 other qualified providers outside CAMH can also do TRS referrals - primary care route has expanded",
  },
  {
    id: "canada-quebec-aide-aux-trans",
    country: "Canada",
    subregion: "Quebec",
    cityName: null,
    orgName: "Aide aux Trans du Quebec",
    category: "crisis",
    contactInfo: "1-855-909-9038 (toll-free), by phone or text, English and French",
    availability: "24/7",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://aideauxtrans.com/en",
    note: null,
  },
  {
    id: "canada-quebec-interligne",
    country: "Canada",
    subregion: "Quebec",
    cityName: null,
    orgName: "Interligne",
    category: "peer",
    contactInfo: "Phone, text, or chat - includes a legal clinic",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.cbrc.net/quebec_gac",
    note: "Offers legal support specifically, useful for the 'legal' category",
  },
  {
    id: "canada-quebec-montreal-montreal-general-hospital-human-sexuality-unit",
    country: "Canada",
    subregion: "Quebec",
    cityName: "Montreal",
    orgName: "Montreal General Hospital Human Sexuality Unit",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.cbrc.net/quebec_gac",
    note: "Gender clinic assessment/hormone/surgery-documentation pathway",
  },
  {
    id: "canada-british-columbia-trans-care-bc",
    country: "Canada",
    subregion: "British Columbia",
    cityName: null,
    orgName: "Trans Care BC",
    category: "general",
    contactInfo: "Health navigation team - see transcarebc.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.transcarebc.ca/",
    note: "Helps find pathways/providers; BC pharmacare began covering most generic estrogen/progesterone from March 2026",
  },
  {
    id: "canada-alberta-skipping-stone-foundation",
    country: "Canada",
    subregion: "Alberta",
    cityName: null,
    orgName: "Skipping Stone Foundation",
    category: "peer",
    contactInfo: "See skippingstone.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.skippingstone.ca/",
    note: "Community + medical navigation + free Trans ID Clinics for legal name/gender marker changes; opening a Calgary trans housing initiative",
  },
  {
    id: "canada-alberta-skipping-stone-trans-id-clinics",
    country: "Canada",
    subregion: "Alberta",
    cityName: null,
    orgName: "Skipping Stone Trans ID Clinics",
    category: "legal",
    contactInfo: "Free, ~1hr appointments, includes notarization support",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.skippingstone.ca/id-clinics",
    note: "Name change / gender marker / ID document support",
  },
  {
    id: "canada-nova-scotia-iwk-health-gender-affirming-care",
    country: "Canada",
    subregion: "Nova Scotia",
    cityName: null,
    orgName: "IWK Health - Gender Affirming Care",
    category: "general",
    contactInfo: "See iwkhealth.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://iwkhealth.ca/clinics-programs-services/gender-affirming-care",
    note: "Youth-focused; psych/counselling/hormone treatment insured if received in publicly funded facilities",
  },
  {
    id: "canada-nova-scotia-pridehealth-nova-scotia-health",
    country: "Canada",
    subregion: "Nova Scotia",
    cityName: null,
    orgName: "prideHealth (Nova Scotia Health)",
    category: "general",
    contactInfo: "See nshealth.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.nshealth.ca/clinics-programs-and-services/pridehealth",
    note: null,
  },
  {
    id: "canada-nova-scotia-cape-breton-cape-breton-transgender-network",
    country: "Canada",
    subregion: "Nova Scotia",
    cityName: "Cape Breton",
    orgName: "Cape Breton Transgender Network",
    category: "peer",
    contactInfo: "See halifaxpride.com/nsresources",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.halifaxpride.com/nsresources",
    note: null,
  },
  {
    id: "canada-new-brunswick-new-brunswick-transgender-health-network",
    country: "Canada",
    subregion: "New Brunswick",
    cityName: null,
    orgName: "New Brunswick Transgender Health Network",
    category: "peer",
    contactInfo: "See CBC coverage / local advocacy channels",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.cbc.ca/news/canada/new-brunswick/calls-for-gender-affirming-care-clinic-provincial-budget-9.7124263",
    note: "New Brunswick is currently the only Atlantic province without a dedicated gender-affirming care clinic. Advocates are pushing for provincial funding to establish one.",
  },
  {
    id: "canada-manitoba-winnipeg-gender-diversity-assessment-and-action-for-youth-gdaay-hsc-winnipeg-children-s-hospital",
    country: "Canada",
    subregion: "Manitoba",
    cityName: "Winnipeg",
    orgName: "Gender Diversity Assessment and Action for Youth (GDAAY), HSC Winnipeg Children's Hospital",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.cbrc.net/gender_affirming_care_services_in_canada_by_province_territory",
    note: "Manitoba's two main trans health clinics (youth + adult) both based in Winnipeg",
  },
  {
    id: "canada-saskatchewan-saskatchewan-health-provincial-gender-affirming-surgery-pathway",
    country: "Canada",
    subregion: "Saskatchewan",
    cityName: null,
    orgName: "Saskatchewan Health provincial gender-affirming surgery pathway",
    category: "general",
    contactInfo: "Some procedures (hysterectomy, mastectomy) provided in-province; more complex ones referred out-of-province",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.cbrc.net/gender_affirming_care_services_in_canada_by_province_territory",
    note: "No single named community org",
  },
  {
    id: "canada-prince-edward-island-gender-affirming-care-pei",
    country: "Canada",
    subregion: "Prince Edward Island",
    cityName: null,
    orgName: "Gender Affirming Care PEI",
    category: "general",
    contactInfo: "See gacpei.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.gacpei.ca/",
    note: "PEI ranked among the best provinces for gender-affirming care coverage, including non-surgical needs like hair removal",
  },
  {
    id: "canada-prince-edward-island-pei-transid-clinic",
    country: "Canada",
    subregion: "Prince Edward Island",
    cityName: null,
    orgName: "PEI TransID Clinic",
    category: "legal",
    contactInfo: "Free clinic for document/ID changes",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.cbc.ca/news/canada/prince-edward-island/pei-transid-clinic-first-time-1.5949533",
    note: null,
  },
  {
    id: "canada-newfoundland-and-labrador-trans-support-nl",
    country: "Canada",
    subregion: "Newfoundland and Labrador",
    cityName: null,
    orgName: "Trans Support NL",
    category: "peer",
    contactInfo: "See tsnl.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://tsnl.org/",
    note: "Advocacy, community building, gender diversity awareness for NL",
  },
  {
    id: "canada-newfoundland-and-labrador-st-john-s-gender-wellness-clinic-janeway-children-s-health-and-rehabilitation-centre",
    country: "Canada",
    subregion: "Newfoundland and Labrador",
    cityName: "St. John's",
    orgName: "Gender Wellness Clinic, Janeway Children's Health and Rehabilitation Centre",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://tsnl.org/transition-nl/",
    note: "Youth-focused; NL expanded surgical coverage in 2019, no longer requires CAMH Toronto evaluation",
  },
  {
    id: "canada-yukon-queer-yukon",
    country: "Canada",
    subregion: "Yukon",
    cityName: null,
    orgName: "Queer Yukon",
    category: "peer",
    contactInfo: "See queeryukon.com",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.queeryukon.com/health-navigation",
    note: "Help with care navigation, documentation, and appointment support",
  },
  {
    id: "canada-yukon-yukon-insured-health-and-hearing-services-gender-affirming-coverage",
    country: "Canada",
    subregion: "Yukon",
    cityName: null,
    orgName: "Yukon Insured Health and Hearing Services - gender affirming coverage",
    category: "general",
    contactInfo: "See yukon.ca",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://yukon.ca/en/health-and-wellness/care-services/learn-about-gender-affirming-care-health-services",
    note: "Reported as one of the most comprehensive gender-affirming coverage policies in Canada since 2021 (WPATH-aligned)",
  },
  {
    id: "canada-northwest-territories-nwt-health-and-social-services-gender-affirming-care-guidelines",
    country: "Canada",
    subregion: "Northwest Territories",
    cityName: null,
    orgName: "NWT Health and Social Services - gender affirming care guidelines",
    category: "general",
    contactInfo: "Referral process via HSS; medical travel benefits for out-of-territory referrals",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.hss.gov.nt.ca/professionals/en/services/health-care-transgender-non-binary-and-gender-nonconforming-people-guidelines-northwest",
    note: null,
  },
  {
    id: "canada-nunavut-government-of-nunavut-transitioning-services-funding",
    country: "Canada",
    subregion: "Nunavut",
    cityName: null,
    orgName: "Government of Nunavut - transitioning services funding",
    category: "general",
    contactInfo: "Health Department partners with Centre de Chirurgie (Montreal) for surgical care",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.transhealthcare.org/news/canada-nation-wide-funding-for-gender-affirming-surgeries/",
    note: null,
  },
  {
    id: "australia-qlife",
    country: "Australia",
    subregion: null,
    cityName: null,
    orgName: "QLife",
    category: "crisis",
    contactInfo: "1800 184 527, phone + webchat",
    availability: "See qlife.org.au; systems reportedly upgrading from July 2026",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://qlife.org.au/",
    note: "Free, anonymous LGBTIQA+ peer support and referral",
  },
  {
    id: "australia-transhub",
    country: "Australia",
    subregion: null,
    cityName: null,
    orgName: "TransHub",
    category: "general",
    contactInfo: "See transhub.org.au",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.transhub.org.au/",
    note: "Digital info/resource platform for trans and gender diverse people, families, allies, providers; has a dedicated crisis page",
  },
  {
    id: "australia-transcend-australia",
    country: "Australia",
    subregion: null,
    cityName: null,
    orgName: "Transcend Australia",
    category: "peer",
    contactInfo: "See transcend.org.au",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transcend.org.au/",
    note: "National community-led family/peer support, education, advocacy",
  },
  {
    id: "australia-new-south-wales-the-gender-centre-inc",
    country: "Australia",
    subregion: "New South Wales",
    cityName: null,
    orgName: "The Gender Centre Inc.",
    category: "general",
    contactInfo: "See gendercentre.org.au",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://gendercentre.org.au/",
    note: "Peak state-wide service: health, advocacy, support, education, homelessness",
  },
  {
    id: "australia-new-south-wales-nsw-specialist-trans-and-gender-diverse-health-service",
    country: "Australia",
    subregion: "New South Wales",
    cityName: null,
    orgName: "NSW Specialist Trans and Gender Diverse Health Service",
    category: "general",
    contactInfo: "Referral required, currently under-25 focus",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.health.nsw.gov.au/lgbtiq-health/Pages/tgd-health-service.aspx",
    note: "NSW/WA removed surgery-or-hormone requirements for changing gender markers on records in 2025",
  },
  {
    id: "australia-victoria-monash-health-gender-clinic",
    country: "Australia",
    subregion: "Victoria",
    cityName: null,
    orgName: "Monash Health Gender Clinic",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://monashhealth.org/services/gender-clinic/",
    note: "Long wait times reported (as of March 2026, booking referrals received Nov 2023)",
  },
  {
    id: "australia-victoria-sexual-health-victoria",
    country: "Australia",
    subregion: "Victoria",
    cityName: null,
    orgName: "Sexual Health Victoria",
    category: "general",
    contactInfo: "See shvic.org.au",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.shvic.org.au/for-you/lesbian-gay-bisexual-transgender-intersex-lgbti/gender-affirming-care/",
    note: "Not accepting new hormone therapy bookings as of 26 Feb 2026 due to demand",
  },
  {
    id: "australia-queensland-gender-service-royal-brisbane-and-women-s-hospital",
    country: "Australia",
    subregion: "Queensland",
    cityName: null,
    orgName: "Gender Service, Royal Brisbane and Women's Hospital",
    category: "general",
    contactInfo: "Available via telehealth statewide",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://metronorth.health.qld.gov.au/rbwh/healthcare-services/gender-service",
    note: "~14 month wait for first appointment reported",
  },
  {
    id: "australia-western-australia-transfolk-wa",
    country: "Australia",
    subregion: "Western Australia",
    cityName: null,
    orgName: "Transfolk WA",
    category: "peer",
    contactInfo: "Peer support for trans people and loved ones",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transformingfamilies.org.au/support/gender-affirming-care-providers-older-teens-young-adults/",
    note: null,
  },
  {
    id: "australia-western-australia-gender-affirming-health-service-wa",
    country: "Australia",
    subregion: "Western Australia",
    cityName: null,
    orgName: "Gender Affirming Health Service (WA)",
    category: "general",
    contactInfo: "Waitlist currently full",
    availability: "Expected to reopen waitlist late 2026",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transformingfamilies.org.au/support/gender-affirming-care-providers-older-teens-young-adults/",
    note: "Flag waitlist-closed status honestly rather than implying open access",
  },
  {
    id: "australia-south-australia-gender-connect-country-sa",
    country: "Australia",
    subregion: "South Australia",
    cityName: null,
    orgName: "Gender Connect Country SA",
    category: "peer",
    contactInfo: "Phone or webchat, peer workers with lived experience",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transformingfamilies.org.au/support/trans-health-south-australia-sa-2/",
    note: "Free, confidential",
  },
  {
    id: "australia-south-australia-sa-health-statewide-gender-diversity-model-of-care",
    country: "Australia",
    subregion: "South Australia",
    cityName: null,
    orgName: "SA Health - Statewide Gender Diversity Model of Care",
    category: "general",
    contactInfo: "Hormone therapy appointments at Modbury Hospital",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.sahealth.sa.gov.au/wps/wcm/connect/public+content/sa+health+internet/services/health+services+for/lgbtiqa+health+services/gender+affirming+services",
    note: null,
  },
  {
    id: "australia-tasmania-working-it-out",
    country: "Australia",
    subregion: "Tasmania",
    cityName: null,
    orgName: "Working It Out",
    category: "peer",
    contactInfo: "One-on-one support and support groups",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.health.tas.gov.au/hospitals/outpatients/clinic-directory/sexual-health-service-tasmania/transgender-services",
    note: "Tasmania's sexuality/gender/intersex support and advocacy service",
  },
  {
    id: "australia-tasmania-tasmanian-gender-service-tgs",
    country: "Australia",
    subregion: "Tasmania",
    cityName: null,
    orgName: "Tasmanian Gender Service (TGS)",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.health.tas.gov.au/health-topics/child-and-youth-health/tasmanian-gender-service-tgs",
    note: "Youth-focused multidisciplinary team",
  },
  {
    id: "australia-australian-capital-territory-a-gender-agenda",
    country: "Australia",
    subregion: "Australian Capital Territory",
    cityName: null,
    orgName: "A Gender Agenda",
    category: "peer",
    contactInfo: "See genderrights.org.au",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://genderrights.org.au/information-hub/organisations-and-services-in-the-act-and-australia/",
    note: "ACT community org + info hub",
  },
  {
    id: "australia-australian-capital-territory-act-human-rights-commission",
    country: "Australia",
    subregion: "Australian Capital Territory",
    cityName: null,
    orgName: "ACT Human Rights Commission",
    category: "legal",
    contactInfo: "Handles discrimination complaints incl. gender identity",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://genderrights.org.au/information-hub/organisations-and-services-in-the-act-and-australia/",
    note: null,
  },
  {
    id: "australia-northern-territory-northern-territory-aids-and-hepatitis-council",
    country: "Australia",
    subregion: "Northern Territory",
    cityName: null,
    orgName: "Northern Territory AIDS and Hepatitis Council",
    category: "peer",
    contactInfo: "Counselling, community support, and more",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://nt.gov.au/wellbeing/transgender-and-gender-diverse-services",
    note: "Offers counselling, community support, and other health services.",
  },
  {
    id: "united-states-trans-lifeline",
    country: "United States",
    subregion: null,
    cityName: null,
    orgName: "Trans Lifeline",
    category: "crisis",
    contactInfo: "(877) 565-8860",
    availability: "Mon-Fri 10am-6pm Pacific / 1-9pm Eastern",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://translifeline.org/hotline/",
    note: "Trans-led peer support and crisis hotline. Limited hours - not 24/7, despite some other listings claiming otherwise.",
  },
  {
    id: "united-states-the-trevor-project",
    country: "United States",
    subregion: null,
    cityName: null,
    orgName: "The Trevor Project",
    category: "crisis",
    contactInfo: "866-488-7386 (866-4-U-TREVOR), or TrevorChat/TrevorText",
    availability: "24/7/365",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.thetrevorproject.org/get-help/",
    note: "LGBTQ youth-focused crisis line",
  },
  {
    id: "united-states-pflag",
    country: "United States",
    subregion: null,
    cityName: null,
    orgName: "PFLAG",
    category: "peer",
    contactInfo: "400+ local chapters - see pflag.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://pflag.org/",
    note: "Family/peer support network, chapters nationwide",
  },
  {
    id: "united-states-advocates-for-trans-equality-a4te-formerly-ncte-tldef",
    country: "United States",
    subregion: null,
    cityName: null,
    orgName: "Advocates for Trans Equality (A4TE, formerly NCTE + TLDEF)",
    category: "legal",
    contactInfo: "See transequality.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transequality.org/",
    note: "National advocacy/legal defense org, merged 2024",
  },
  {
    id: "united-states-california-transgender-health-wellness-center",
    country: "United States",
    subregion: "California",
    cityName: null,
    orgName: "Transgender Health & Wellness Center",
    category: "peer",
    contactInfo: "Southern California - see org site",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.dmhc.ca.gov/HealthCareinCalifornia/GettheBestCare/TGICare.aspx",
    note: "Largest trans-led org in the region; social services, housing, employment, legal guidance, counselling",
  },
  {
    id: "united-states-california-sacramento-gender-health-center",
    country: "United States",
    subregion: "California",
    cityName: "Sacramento",
    orgName: "Gender Health Center",
    category: "general",
    contactInfo: "Free/low-cost clinic",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.genderhealthcenter.org/",
    note: "Free health clinic, mental health counselling, support groups, legal assistance, case management",
  },
  {
    id: "united-states-california-california-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "California",
    cityName: null,
    orgName: "California ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.lgbtmap.org/equality-maps/healthcare_laws_and_policies",
    note: "Per MAP/KFF trackers as of this research",
  },
  {
    id: "united-states-new-york-acr-health-trans-resource-guide",
    country: "United States",
    subregion: "New York",
    cityName: null,
    orgName: "ACR Health Trans Resource Guide",
    category: "general",
    contactInfo: "See acrhealth.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.trans.health/",
    note: null,
  },
  {
    id: "united-states-new-york-albany-prism-albany",
    country: "United States",
    subregion: "New York",
    cityName: "Albany",
    orgName: "Prism Albany",
    category: "peer",
    contactInfo: "See local listings",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.trans.health/",
    note: null,
  },
  {
    id: "united-states-new-york-new-york-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "New York",
    cityName: null,
    orgName: "New York ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.lgbtmap.org/equality-maps/healthcare_laws_and_policies",
    note: "Per MAP/KFF trackers as of this research",
  },
  {
    id: "united-states-illinois-transgender-gender-diverse-tgd-wellness-and-equity-program",
    country: "United States",
    subregion: "Illinois",
    cityName: null,
    orgName: "Transgender/Gender Diverse (TGD) Wellness and Equity Program",
    category: "general",
    contactInfo: "Illinois Dept of Human Services + Public Health Institute of Metropolitan Chicago",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.dhs.state.il.us/page.aspx?item=168694",
    note: "Statewide initiative",
  },
  {
    id: "united-states-illinois-equality-illinois",
    country: "United States",
    subregion: "Illinois",
    cityName: null,
    orgName: "Equality Illinois",
    category: "legal",
    contactInfo: "See equalityillinois.us",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://phimc.org/initiatives/tgd-wellness-and-equity-program/",
    note: "Statewide LGBTQ+ advocacy",
  },
  {
    id: "united-states-illinois-chicago-trans-care-clinic-for-affirmation-and-reproductive-equity-uchicago-medicine",
    country: "United States",
    subregion: "Illinois",
    cityName: "Chicago",
    orgName: "Trans CARE (Clinic for Affirmation and Reproductive Equity), UChicago Medicine",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.uchicagomedicine.org/conditions-services/transgender-care-services/trans-care",
    note: null,
  },
  {
    id: "united-states-massachusetts-massachusetts-transgender-political-coalition",
    country: "United States",
    subregion: "Massachusetts",
    cityName: null,
    orgName: "Massachusetts Transgender Political Coalition",
    category: "legal",
    contactInfo: "Gender marker/name change support, emergency financial assistance",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.massgeneral.org/transgender-health-program/resources/individuals",
    note: null,
  },
  {
    id: "united-states-massachusetts-boston-fenway-health-sidney-borum-jr-health-program",
    country: "United States",
    subregion: "Massachusetts",
    cityName: "Boston",
    orgName: "Fenway Health - Sidney Borum Jr. Health Program",
    category: "general",
    contactInfo: "For LGBTQ+ people aged 12-29",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.massgeneral.org/transgender-health-program/resources/individuals",
    note: null,
  },
  {
    id: "united-states-massachusetts-boston-boston-alliance-of-lgbtq-youth-bagly",
    country: "United States",
    subregion: "Massachusetts",
    cityName: "Boston",
    orgName: "Boston Alliance of LGBTQ+ Youth (BAGLY)",
    category: "peer",
    contactInfo: "See bagly.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.massgeneral.org/transgender-health-program/resources/individuals",
    note: null,
  },
  {
    id: "united-states-texas-transgender-education-network-of-texas-tent",
    country: "United States",
    subregion: "Texas",
    cityName: null,
    orgName: "Transgender Education Network of Texas (TENT)",
    category: "peer",
    contactInfo: "See txtrans.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tx/",
    note: null,
  },
  {
    id: "united-states-texas-equality-texas",
    country: "United States",
    subregion: "Texas",
    cityName: null,
    orgName: "Equality Texas",
    category: "legal",
    contactInfo: "See equalitytexas.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tx/",
    note: null,
  },
  {
    id: "united-states-texas-trans-youth-emergency-project-campaign-for-southern-equality",
    country: "United States",
    subregion: "Texas",
    cityName: null,
    orgName: "Trans Youth Emergency Project (Campaign for Southern Equality)",
    category: "general",
    contactInfo: "1-on-1 family navigation + renewable $500 travel grants",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tyep/",
    note: "For families of trans youth affected by the ban, covers travel to access care out-of-state",
  },
  {
    id: "united-states-florida-campaign-for-southern-equality-florida-resources",
    country: "United States",
    subregion: "Florida",
    cityName: null,
    orgName: "Campaign for Southern Equality - Florida resources",
    category: "general",
    contactInfo: "See southernequality.org/fl/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/fl/",
    note: "Family navigation resources for trans youth in FL",
  },
  {
    id: "united-states-florida-aclu-of-florida-gender-affirming-care-resources-guide",
    country: "United States",
    subregion: "Florida",
    cityName: null,
    orgName: "ACLU of Florida - Gender-Affirming Care Resources guide",
    category: "legal",
    contactInfo: "PDF resource guide",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.aclufl.org/app/uploads/2026/01/Gendering-Affirming-Care-Florida-Resources-Print-V2.pdf",
    note: null,
  },
  {
    id: "united-states-colorado-transgender-center-of-the-rockies",
    country: "United States",
    subregion: "Colorado",
    cityName: null,
    orgName: "Transgender Center of the Rockies",
    category: "general",
    contactInfo: "Clinical groups, individual counselling, peer-led support groups, PrEP case management",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.transgendercenteroftherockies.org/",
    note: null,
  },
  {
    id: "united-states-colorado-denver-the-center-on-colfax",
    country: "United States",
    subregion: "Colorado",
    cityName: "Denver",
    orgName: "The Center on Colfax",
    category: "peer",
    contactInfo: "Weekly trans social/support programs, legal department",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://lgbtqcolorado.org/resource-guide/gender-affirming-care/",
    note: "Age-specific groups: SAGE (50+), SAGA (18-24), Rainbow Alley (10-17)",
  },
  {
    id: "united-states-colorado-colorado-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "Colorado",
    cityName: null,
    orgName: "Colorado ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transaware.net/most-welcoming-supportive-us-states-for-trans-people/",
    note: "Per trackers as of this research",
  },
  {
    id: "united-states-oregon-ohsu-transgender-health-program",
    country: "United States",
    subregion: "Oregon",
    cityName: null,
    orgName: "OHSU Transgender Health Program",
    category: "general",
    contactInfo: "Care across 7 cities in Oregon and SW Washington",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.ohsu.edu/transgender-health",
    note: null,
  },
  {
    id: "united-states-oregon-portland-transactive-gender-project",
    country: "United States",
    subregion: "Oregon",
    cityName: "Portland",
    orgName: "TransActive Gender Project",
    category: "peer",
    contactInfo: "Support groups for families of trans/gender-diverse youth ages 4-18",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.doj.state.or.us/oregon-department-of-justice/civil-rights/gender-diverse-community-resources/",
    note: null,
  },
  {
    id: "united-states-oregon-eugene-trans-ponder",
    country: "United States",
    subregion: "Oregon",
    cityName: "Eugene",
    orgName: "Trans*Ponder",
    category: "peer",
    contactInfo: "Support, education, advocacy",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.doj.state.or.us/oregon-department-of-justice/civil-rights/gender-diverse-community-resources/",
    note: null,
  },
  {
    id: "united-states-washington-ohsu-transgender-health-program-serves-sw-washington",
    country: "United States",
    subregion: "Washington",
    cityName: null,
    orgName: "OHSU Transgender Health Program (serves SW Washington)",
    category: "general",
    contactInfo: "See ohsu.edu",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.ohsu.edu/transgender-health",
    note: null,
  },
  {
    id: "united-states-washington-washington-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "Washington",
    cityName: null,
    orgName: "Washington ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transaware.net/most-welcoming-supportive-us-states-for-trans-people/",
    note: "Per trackers as of this research",
  },
  {
    id: "united-states-new-jersey-proud-gender-center-robert-wood-johnson-university-hospital",
    country: "United States",
    subregion: "New Jersey",
    cityName: null,
    orgName: "PROUD Gender Center (Robert Wood Johnson University Hospital)",
    category: "general",
    contactInfo: "1-833-247-7683, ages 19+",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.rwjbh.org/rwj-university-hospital-new-brunswick/treatment-care/lgbtqia-program/proud-gender-center-transgender-community-servic/",
    note: null,
  },
  {
    id: "united-states-new-jersey-new-jersey-support-group",
    country: "United States",
    subregion: "New Jersey",
    cityName: null,
    orgName: "New Jersey Support Group",
    category: "peer",
    contactInfo: "Monthly meetings, first Saturday 5:30-8pm, Washington's Crossing NJ",
    availability: "Monthly",
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.njsg.org/",
    note: null,
  },
  {
    id: "united-states-new-jersey-rutgers-center-for-transgender-health",
    country: "United States",
    subregion: "New Jersey",
    cityName: null,
    orgName: "Rutgers Center for Transgender Health",
    category: "general",
    contactInfo: "Referral required",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.nj.gov/transgender/support-resources/medical-support.shtml",
    note: null,
  },
  {
    id: "united-states-connecticut-ct-dmhas-lgbtq-services",
    country: "United States",
    subregion: "Connecticut",
    cityName: null,
    orgName: "CT DMHAS LGBTQ+ Services",
    category: "general",
    contactInfo: "See portal.ct.gov/DMHAS",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://portal.ct.gov/DMHAS/Programs-and-Services/Finding-Services/LGBT-Services",
    note: null,
  },
  {
    id: "united-states-connecticut-connecticut-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "Connecticut",
    cityName: null,
    orgName: "Connecticut ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.lgbtmap.org/equality-maps/healthcare_laws_and_policies",
    note: "Per trackers as of this research",
  },
  {
    id: "united-states-maryland-trans-maryland",
    country: "United States",
    subregion: "Maryland",
    cityName: null,
    orgName: "Trans Maryland",
    category: "peer",
    contactInfo: "Document assistance clinics for name/gender marker changes",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://transmaryland.org/",
    note: "Multi-racial, multi-gender, trans-led",
  },
  {
    id: "united-states-maryland-maryland-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "Maryland",
    cityName: null,
    orgName: "Maryland ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.lgbtmap.org/equality-maps/healthcare_laws_and_policies",
    note: "Per trackers as of this research",
  },
  {
    id: "united-states-pennsylvania-the-welcome-project-pa",
    country: "United States",
    subregion: "Pennsylvania",
    cityName: null,
    orgName: "The Welcome Project PA",
    category: "peer",
    contactInfo: "See welcomeprojectpa.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://welcomeprojectpa.org/lgbt-about/trans-care-resources/",
    note: null,
  },
  {
    id: "united-states-pennsylvania-gender-health-clinic-penn-state-health-golisano-children-s-hospital",
    country: "United States",
    subregion: "Pennsylvania",
    cityName: null,
    orgName: "Gender Health Clinic, Penn State Health Golisano Children's Hospital",
    category: "general",
    contactInfo: "Youth psychosocial care; separate adult care 19+",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.pennstatehealth.org/services-treatments/care-transgender-gender-diverse-individuals",
    note: null,
  },
  {
    id: "united-states-pennsylvania-pittsburgh-central-outreach-wellness-center",
    country: "United States",
    subregion: "Pennsylvania",
    cityName: "Pittsburgh",
    orgName: "Central Outreach Wellness Center",
    category: "general",
    contactInfo: "Consent-based gender-affirming care",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.centraloutreach.com/services/gender-affirming-care",
    note: null,
  },
  {
    id: "united-states-ohio-transohio",
    country: "United States",
    subregion: "Ohio",
    cityName: null,
    orgName: "TransOhio",
    category: "peer",
    contactInfo: "Services, education, support, advocacy",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.transohio.org/",
    note: null,
  },
  {
    id: "united-states-ohio-columbus-stonewall-columbus-trans-resource-directory",
    country: "United States",
    subregion: "Ohio",
    cityName: "Columbus",
    orgName: "Stonewall Columbus Trans Resource Directory",
    category: "general",
    contactInfo: "Directory of local providers",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://stonewallcolumbus.org/trans-resource-directory/",
    note: null,
  },
  {
    id: "united-states-michigan-gender-identity-network-alliance-gna",
    country: "United States",
    subregion: "Michigan",
    cityName: null,
    orgName: "Gender Identity Network Alliance (GNA)",
    category: "peer",
    contactInfo: "Advocacy, support groups, education",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.aclumich.org/transgender-and-lgbtq-support-organizations-michigan/",
    note: null,
  },
  {
    id: "united-states-michigan-grand-rapids-grand-rapids-trans-foundation",
    country: "United States",
    subregion: "Michigan",
    cityName: "Grand Rapids",
    orgName: "Grand Rapids Trans Foundation",
    category: "general",
    contactInfo: "Scholarship funds for trans/nonbinary students",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.aclumich.org/transgender-and-lgbtq-support-organizations-michigan/",
    note: null,
  },
  {
    id: "united-states-michigan-greater-michigan-gender-services",
    country: "United States",
    subregion: "Michigan",
    cityName: null,
    orgName: "Greater Michigan Gender Services",
    category: "general",
    contactInfo: "See migender.com",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://migender.com/",
    note: null,
  },
  {
    id: "united-states-georgia-campaign-for-southern-equality-georgia",
    country: "United States",
    subregion: "Georgia",
    cityName: null,
    orgName: "Campaign for Southern Equality - Georgia",
    category: "general",
    contactInfo: "See southernequality.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/transadultcare/",
    note: "Part of a 13-state Southern regional network tracking adult care access, covering Alabama, Arkansas, Florida, Georgia, Kentucky, Louisiana, Mississippi, North Carolina, South Carolina, Tennessee, Texas, Virginia, and West Virginia.",
  },
  {
    id: "united-states-north-carolina-campaign-for-southern-equality-north-carolina",
    country: "United States",
    subregion: "North Carolina",
    cityName: null,
    orgName: "Campaign for Southern Equality - North Carolina",
    category: "general",
    contactInfo: "See southernequality.org/nc/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/nc/",
    note: "Resources, training, direct support to trans individuals and families",
  },
  {
    id: "united-states-north-carolina-organizations-in-nc-serving-the-transgender-community-qnotes-carolinas-directory",
    country: "United States",
    subregion: "North Carolina",
    cityName: null,
    orgName: "Organizations in NC serving the transgender community (Qnotes Carolinas directory)",
    category: "peer",
    contactInfo: "See qnotescarolinas.com",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://qnotescarolinas.com/transgender-resources-north-carolina/",
    note: null,
  },
  {
    id: "united-states-south-carolina-resources-for-transgender-adults-in-south-carolina-campaign-for-southern-equality",
    country: "United States",
    subregion: "South Carolina",
    cityName: null,
    orgName: "Resources for Transgender Adults in South Carolina (Campaign for Southern Equality)",
    category: "general",
    contactInfo: "See southernequality.org/schealthcarehelp/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/schealthcarehelp/",
    note: "Specifically addresses adults impacted by H.4624",
  },
  {
    id: "united-states-tennessee-campaign-for-southern-equality-tennessee",
    country: "United States",
    subregion: "Tennessee",
    cityName: null,
    orgName: "Campaign for Southern Equality - Tennessee",
    category: "general",
    contactInfo: "See southernequality.org/tn/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tn/",
    note: null,
  },
  {
    id: "united-states-kentucky-campaign-for-southern-equality-regional-network",
    country: "United States",
    subregion: "Kentucky",
    cityName: null,
    orgName: "Campaign for Southern Equality regional network",
    category: "general",
    contactInfo: "See southernequality.org/transadultcare/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/transadultcare/",
    note: "No Kentucky-specific named community org",
  },
  {
    id: "united-states-alabama-campaign-for-southern-equality-regional-network",
    country: "United States",
    subregion: "Alabama",
    cityName: null,
    orgName: "Campaign for Southern Equality regional network",
    category: "general",
    contactInfo: "See southernequality.org/transadultcare/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/transadultcare/",
    note: "No Alabama-specific named community org",
  },
  {
    id: "united-states-mississippi-campaign-for-southern-equality-regional-network",
    country: "United States",
    subregion: "Mississippi",
    cityName: null,
    orgName: "Campaign for Southern Equality regional network",
    category: "general",
    contactInfo: "See southernequality.org/transadultcare/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/transadultcare/",
    note: "No Mississippi-specific named community org",
  },
  {
    id: "united-states-virginia-virginia-dept-of-health-transgender-resource-and-referral-list",
    country: "United States",
    subregion: "Virginia",
    cityName: null,
    orgName: "Virginia Dept of Health - Transgender Resource and Referral List",
    category: "general",
    contactInfo: "PDF directory, updated May 2026",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.vdh.virginia.gov/content/uploads/sites/10/2025/06/TransRRList.pdf",
    note: "Comprehensive official state-maintained resource list - good source to mine further",
  },
  {
    id: "united-states-virginia-transgender-assistance-program-of-virginia-tap-va",
    country: "United States",
    subregion: "Virginia",
    cityName: null,
    orgName: "Transgender Assistance Program of Virginia (TAP VA)",
    category: "housing",
    contactInfo: "All-volunteer, trans-led, focused on ending trans homelessness in VA",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://tapvirginia.org/resources",
    note: null,
  },
  {
    id: "united-states-virginia-equality-virginia",
    country: "United States",
    subregion: "Virginia",
    cityName: null,
    orgName: "Equality Virginia",
    category: "legal",
    contactInfo: "Statewide advocacy org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://tapvirginia.org/resources",
    note: null,
  },
  {
    id: "united-states-nevada-nv-gender-clinic",
    country: "United States",
    subregion: "Nevada",
    cityName: null,
    orgName: "NV Gender Clinic",
    category: "general",
    contactInfo: "Connects clients to affirming providers statewide",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.nvgenderclinic.com/",
    note: null,
  },
  {
    id: "united-states-nevada-las-vegas-gender-diverse-and-transpride-center-of-southern-nevada",
    country: "United States",
    subregion: "Nevada",
    cityName: "Las Vegas",
    orgName: "Gender Diverse and Transpride Center of Southern Nevada",
    category: "peer",
    contactInfo: "Financial, emotional, physical, educational support",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.gdtpc.org/",
    note: null,
  },
  {
    id: "united-states-nevada-reno-barry-frank-family-gender-and-sexual-healthcare-clinic-northern-nevada-hopes",
    country: "United States",
    subregion: "Nevada",
    cityName: "Reno",
    orgName: "Barry Frank Family Gender and Sexual Healthcare Clinic (Northern Nevada HOPES)",
    category: "general",
    contactInfo: "Case management + financial support for transitioning",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.nnhopes.org/patients/health-services/lgbtq-health/",
    note: null,
  },
  {
    id: "united-states-minnesota-minnesota-transgender-health-coalition",
    country: "United States",
    subregion: "Minnesota",
    cityName: null,
    orgName: "Minnesota Transgender Health Coalition",
    category: "peer",
    contactInfo: "Education, resources, advocacy",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.mntransgenderhealth.org/",
    note: null,
  },
  {
    id: "united-states-minnesota-family-tree-clinic",
    country: "United States",
    subregion: "Minnesota",
    cityName: null,
    orgName: "Family Tree Clinic",
    category: "general",
    contactInfo: "Helps find affirming local resources",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.familytreeclinic.org/trans-resources/",
    note: null,
  },
  {
    id: "united-states-minnesota-minnesota-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "Minnesota",
    cityName: null,
    orgName: "Minnesota ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.lgbtmap.org/equality-maps/healthcare_laws_and_policies",
    note: "Per trackers as of this research",
  },
  {
    id: "united-states-wisconsin-trans-law-help-wisconsin",
    country: "United States",
    subregion: "Wisconsin",
    cityName: null,
    orgName: "Trans Law Help Wisconsin",
    category: "legal",
    contactInfo: "See Fair Wisconsin for referral",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.plannedparenthood.org/planned-parenthood-wisconsin/patients/gender-affirming-care/wisconsin-national-tng-resource-list",
    note: null,
  },
  {
    id: "united-states-wisconsin-fair-wisconsin",
    country: "United States",
    subregion: "Wisconsin",
    cityName: null,
    orgName: "Fair Wisconsin",
    category: "legal",
    contactInfo: "Statewide LGBTQ+ advocacy",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.plannedparenthood.org/planned-parenthood-wisconsin/patients/gender-affirming-care/wisconsin-national-tng-resource-list",
    note: null,
  },
  {
    id: "united-states-new-mexico-transgender-resource-center-of-new-mexico",
    country: "United States",
    subregion: "New Mexico",
    cityName: null,
    orgName: "Transgender Resource Center of New Mexico",
    category: "peer",
    contactInfo: "Direct services, education, advocacy, name/gender marker ID help",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://tgrcnm.org/",
    note: null,
  },
  {
    id: "united-states-new-mexico-new-mexico-ranked-among-the-most-protective-shield-law-states",
    country: "United States",
    subregion: "New Mexico",
    cityName: null,
    orgName: "New Mexico ranked among the most protective 'shield law' states",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.lgbtmap.org/equality-maps/healthcare_laws_and_policies",
    note: "Per trackers as of this research",
  },
  {
    id: "united-states-louisiana-louisiana-trans-advocates",
    country: "United States",
    subregion: "Louisiana",
    cityName: null,
    orgName: "Louisiana Trans Advocates",
    category: "peer",
    contactInfo: "See latransadvocates.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.latransadvocates.org/healthcare-ban-faq",
    note: "Maintains a healthcare-ban FAQ specifically",
  },
  {
    id: "united-states-louisiana-campaign-for-southern-equality-louisiana-with-rejac",
    country: "United States",
    subregion: "Louisiana",
    cityName: null,
    orgName: "Campaign for Southern Equality - Louisiana (with ReJAC)",
    category: "general",
    contactInfo: "See southernequality.org/la/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/la/",
    note: "CSE also runs a fund to support LA residents accessing care in non-banned states",
  },
  {
    id: "united-states-arkansas-campaign-for-southern-equality-regional-network",
    country: "United States",
    subregion: "Arkansas",
    cityName: null,
    orgName: "Campaign for Southern Equality regional network",
    category: "general",
    contactInfo: "See southernequality.org/transadultcare/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/transadultcare/",
    note: "No Arkansas-specific named community org",
  },
  {
    id: "united-states-idaho-campaign-for-southern-equality-idaho-trans-youth-emergency-project",
    country: "United States",
    subregion: "Idaho",
    cityName: null,
    orgName: "Campaign for Southern Equality - Idaho (Trans Youth Emergency Project)",
    category: "general",
    contactInfo: "See southernequality.org/id/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/id/",
    note: "TYEP operates here despite the 'southern' name - covers ID, MT, UT, WY too",
  },
  {
    id: "united-states-utah-trans-youth-emergency-project-regional-coverage",
    country: "United States",
    subregion: "Utah",
    cityName: null,
    orgName: "Trans Youth Emergency Project (regional coverage)",
    category: "general",
    contactInfo: "See southernequality.org/tyep/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tyep/",
    note: null,
  },
  {
    id: "united-states-montana-trans-youth-emergency-project-regional-coverage",
    country: "United States",
    subregion: "Montana",
    cityName: null,
    orgName: "Trans Youth Emergency Project (regional coverage)",
    category: "general",
    contactInfo: "See southernequality.org/tyep/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tyep/",
    note: "No Montana-specific named community org",
  },
  {
    id: "united-states-wyoming-trans-youth-emergency-project-regional-coverage",
    country: "United States",
    subregion: "Wyoming",
    cityName: null,
    orgName: "Trans Youth Emergency Project (regional coverage)",
    category: "general",
    contactInfo: "See southernequality.org/tyep/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/tyep/",
    note: "No Wyoming-specific named community org",
  },
  {
    id: "united-states-iowa-one-iowa",
    country: "United States",
    subregion: "Iowa",
    cityName: null,
    orgName: "One Iowa",
    category: "peer",
    contactInfo: "See oneiowa.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://oneiowa.org/resources/transresources/",
    note: "Trans and nonbinary resources directory",
  },
  {
    id: "united-states-iowa-iowa-trans-mutual-aid-fund",
    country: "United States",
    subregion: "Iowa",
    cityName: null,
    orgName: "Iowa Trans Mutual Aid Fund",
    category: "general",
    contactInfo: "Financial assistance for accessing gender-affirming care",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://oneiowa.org/resources/transresources/",
    note: null,
  },
  {
    id: "united-states-oklahoma-freedom-oklahoma",
    country: "United States",
    subregion: "Oklahoma",
    cityName: null,
    orgName: "Freedom Oklahoma",
    category: "legal",
    contactInfo: "Statewide LGBTQ+ advocacy",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://heartlandsignal.com/2026/05/23/new-laws-impact-foster-care-children-gender-affirming-care-for-oklahoma-adults/",
    note: null,
  },
  {
    id: "united-states-vermont-pride-center-of-vermont",
    country: "United States",
    subregion: "Vermont",
    cityName: null,
    orgName: "Pride Center of Vermont",
    category: "peer",
    contactInfo: "Multiple programs incl. Transpire (trans/intersex/gender-nonconforming community)",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.pridecentervt.org/programs/transprogram/",
    note: "Described as New England's most comprehensive LGBTQ community center",
  },
  {
    id: "united-states-vermont-vermont-diversity-health-project",
    country: "United States",
    subregion: "Vermont",
    cityName: null,
    orgName: "Vermont Diversity Health Project",
    category: "general",
    contactInfo: "Helps identify affirming healthcare providers",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://women.vermont.gov/lgbtqia",
    note: null,
  },
  {
    id: "united-states-new-hampshire-gender-diverse-care-coalition-nh",
    country: "United States",
    subregion: "New Hampshire",
    cityName: null,
    orgName: "Gender Diverse Care Coalition NH",
    category: "general",
    contactInfo: "See genderdiversecarecoalitionnh.com",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://genderdiversecarecoalitionnh.com/gender-affirmative-resources-in-nh-and-surrounding-areas/",
    note: null,
  },
  {
    id: "united-states-new-hampshire-dartmouth-health-children-s-gender-care",
    country: "United States",
    subregion: "New Hampshire",
    cityName: null,
    orgName: "Dartmouth Health Children's Gender Care",
    category: "general",
    contactInfo: "Only comprehensive pediatric/adolescent gender care program in NH",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://childrens.dartmouth-health.org/gender-care",
    note: "Also serves VT, northern MA, ME",
  },
  {
    id: "united-states-maine-mainetrans-net",
    country: "United States",
    subregion: "Maine",
    cityName: null,
    orgName: "Mainetrans.net",
    category: "peer",
    contactInfo: "Peer-to-peer support groups, community events, advocacy",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://mainetrans.net/",
    note: "Led by trans people for trans people",
  },
  {
    id: "united-states-rhode-island-adult-gender-and-sexuality-behavioral-health-program-lifespan",
    country: "United States",
    subregion: "Rhode Island",
    cityName: null,
    orgName: "Adult Gender and Sexuality Behavioral Health Program (Lifespan)",
    category: "general",
    contactInfo: "For adults 18+",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://health.ri.gov/health-equity/sogi-equity/partners-additional-resources",
    note: null,
  },
  {
    id: "united-states-rhode-island-open-door-health",
    country: "United States",
    subregion: "Rhode Island",
    cityName: null,
    orgName: "Open Door Health",
    category: "general",
    contactInfo: "RI Public Health Institute's LGBTQ+ health clinic",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://translifeline.org/resource_category/rhode-island/",
    note: null,
  },
  {
    id: "united-states-west-virginia-campaign-for-southern-equality-regional-network",
    country: "United States",
    subregion: "West Virginia",
    cityName: null,
    orgName: "Campaign for Southern Equality regional network",
    category: "general",
    contactInfo: "See southernequality.org/transadultcare/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/transadultcare/",
    note: "No WV-specific named community org",
  },
  {
    id: "united-states-north-dakota-campaign-for-southern-equality-north-dakota-with-nd-human-rights-coalition",
    country: "United States",
    subregion: "North Dakota",
    cityName: null,
    orgName: "Campaign for Southern Equality - North Dakota (with ND Human Rights Coalition)",
    category: "general",
    contactInfo: "See southernequality.org/nd/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/nd/",
    note: null,
  },
  {
    id: "united-states-nebraska-campaign-for-southern-equality-nebraska-with-outnebraska",
    country: "United States",
    subregion: "Nebraska",
    cityName: null,
    orgName: "Campaign for Southern Equality - Nebraska (with OutNebraska)",
    category: "general",
    contactInfo: "See southernequality.org/ne/",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://southernequality.org/ne/",
    note: null,
  },
  {
    id: "united-states-hawaii-kua-ana-project-hhhrc",
    country: "United States",
    subregion: "Hawaii",
    cityName: null,
    orgName: "Kua'ana Project (HHHRC)",
    category: "peer",
    contactInfo: "(808) 521-2437, kuaana@hhhrc.org",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.hhhrc.org/transgender",
    note: "Peer support: job searches, name changes, stable housing access",
  },
  {
    id: "united-states-hawaii-hawaii-gender-echo-program-g-echo",
    country: "United States",
    subregion: "Hawaii",
    cityName: null,
    orgName: "Hawaii Gender ECHO Program (G-ECHO)",
    category: "general",
    contactInfo: "Curated provider list for families, updated May 2026",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://health.hawaii.gov/harmreduction/new-gender-affirming-providers-directory/",
    note: null,
  },
  {
    id: "united-states-hawaii-gender-affirming-treatment-act-gata-hawaii-state-law",
    country: "United States",
    subregion: "Hawaii",
    cityName: null,
    orgName: "Gender Affirming Treatment Act (GATA) - Hawaii state law",
    category: "legal",
    contactInfo: "n/a",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://health.hawaii.gov/camhd/lgbtq-safe-spaces/",
    note: "Hawaii is protective by state law, expanding access for youth and adults - a contrast to many other states in this research.",
  },
  {
    id: "united-states-delaware-camp-rehoboth",
    country: "United States",
    subregion: "Delaware",
    cityName: null,
    orgName: "CAMP Rehoboth",
    category: "peer",
    contactInfo: "Community programs, education, health services incl. counselling/support groups",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.outcarehealth.org/resources/",
    note: null,
  },
  {
    id: "united-states-delaware-aids-delaware",
    country: "United States",
    subregion: "Delaware",
    cityName: null,
    orgName: "AIDS Delaware",
    category: "general",
    contactInfo: "HIV testing, support groups",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.outcarehealth.org/resources/",
    note: "Primarily HIV-focused but relevant peer/health support",
  },
  {
    id: "united-states-alaska-alaskan-aids-assistance-association-four-a-s",
    country: "United States",
    subregion: "Alaska",
    cityName: null,
    orgName: "Alaskan AIDS Assistance Association (Four A's)",
    category: "general",
    contactInfo: "HIV testing, medical case management",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.outcarehealth.org/resources/",
    note: "Primarily HIV-focused",
  },
  {
    id: "united-states-alaska-anchorage-providence-alaska-medical-center",
    country: "United States",
    subregion: "Alaska",
    cityName: "Anchorage",
    orgName: "Providence Alaska Medical Center",
    category: "general",
    contactInfo: "Primary care, hormone therapy, behavioral health, social work",
    availability: null,
    lastReviewedAt: "2026-07-17",
    sourceUrl: "https://www.outcarehealth.org/resources/",
    note: null,
  },
];

const FALLBACK_LEGAL_CONTEXT_NOTES: LegalContextNote[] = [
{
    country: "Australia",
    subregion: "Northern Territory",
    note: "There are currently no adult gender-affirming care clinics based in the Northern Territory - care is accessed via telehealth or referral. The NT Health Minister has also restricted public-system access to puberty blockers and hormone therapy for adolescents.",
    sourceUrl: "https://nt.gov.au/wellbeing/transgender-and-gender-diverse-services",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "Australia",
    subregion: "Queensland",
    note: "Queensland's public healthcare system currently restricts gender-affirming care for transgender youth. A legal challenge against this restriction was filed in the Queensland Supreme Court in January 2026.",
    sourceUrl: "https://transcend.org.au/latest-news/healthcare-is-a-human-right-standing-with-trans-young-people-in-queensland/",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Texas",
    note: "Texas law (SB14) currently bans gender-affirming care for people under 18. The Texas Senate has also passed a bill that would extend restrictions to adults.",
    sourceUrl: "https://www.hrc.org/press-releases/texas-senate-passes-sweeping-ban-to-prohibit-trans-youth-and-adults-from-receiving-necessary-medical-care",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Florida",
    note: "Florida law (SB254, 2023) currently bans gender-affirming care for people under 18. Further restrictions have been reported moving through the Florida Senate.",
    sourceUrl: "https://www.hrc.org/press-releases/breaking-florida-senate-passes-extreme-gender-affirming-care-ban",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Georgia",
    note: "Georgia has banned gender-affirming care for minors since 2023. A bill has also been filed to ban puberty blockers, which had previously remained allowed.",
    sourceUrl: "https://qnotescarolinas.com/transgender-resources-north-carolina/",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "North Carolina",
    note: "North Carolina law (HB808) bans starting gender-affirming care (puberty blockers, hormones, or surgery) for people under 18.",
    sourceUrl: "https://southernequality.org/nc/",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "South Carolina",
    note: "South Carolina's ban (H.4624) restricts care for youth and reportedly also prohibits public funds from being used for gender-affirming care at any age. It's currently under legal challenge from the ACLU.",
    sourceUrl: "https://www.aclu.org/press-releases/trans-people-families-file-lawsuit-against-south-carolinas-gender-affirming-care-ban",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Tennessee",
    note: "Tennessee law (SB1/HB1) bans gender-affirming care for people under 18 - this was the law upheld by the US Supreme Court in the 2025 Skrmetti decision. Tennessee is also reported to be expanding Medicaid restrictions on this care for adults.",
    sourceUrl: "https://www.aclu.org/press-releases/sixth-circuit-allows-tennessees-ban-on-care-for-transgender-youth-to-take-effect",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Kentucky",
    note: "Kentucky is reported to be expanding Medicaid restrictions on gender-affirming care for adults, and is among states that restrict this care for incarcerated people.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Alabama",
    note: "Alabama has an active ban on gender-affirming care for transgender youth.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Mississippi",
    note: "Mississippi has an existing ban on gender-affirming care for youth, and is reported to be expanding Medicaid restrictions for adults this legislative session.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Virginia",
    note: "As restrictions have expanded across the South, Virginia has been reported as one of the few remaining states in the region where gender-affirming care access continues.",
    sourceUrl: "https://www.hrc.org/press-releases/south-carolina-legislature-passes-ban-on-gender-affirming-care-for-transgender-youth-virginia-poised-to-be-the-sole-refuge-for-care-in-the-south",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Louisiana",
    note: "Louisiana's HB648 (youth ban) has been in effect since January 2024. The state legislature has since overridden a governor's veto on further restrictions.",
    sourceUrl: "https://www.hrc.org/press-releases/breaking-louisiana-legislators-override-governors-veto-of-extreme-gender-affirming-care-ban",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Arkansas",
    note: "Arkansas's legal history here is unusually tangled: a 2021 ban was blocked by a federal court in 2023, but the state passed a separate law allowing former providers to be sued for care given to minors, and a federal appeals court has since upheld a ban. Current status is genuinely unclear.",
    sourceUrl: "https://www.aclu.org/press-releases/eighth-circuit-upholds-arkansass-ban-on-gender-affirming-care-for-transgender-youth",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Missouri",
    note: "Missouri's current restriction on gender-affirming care for minors is set to expire in 2027. The state legislature is considering bills to make the ban permanent.",
    sourceUrl: "https://www.kcur.org/politics-elections-and-government/2026-02-12/missouri-house-transgender-health-care-gender-affirming-minors",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Idaho",
    note: "Idaho law (HB71, upheld by the US Supreme Court) bans gender-affirming care for youth, and a separate law (HB668) bars any public funds from being used for this care at any age.",
    sourceUrl: "https://feminist.org/news/supreme-court-votes-to-uphold-idaho-bill-banning-gender-affirming-healthcare-for-lgbtq-youth/",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Utah",
    note: "Utah bans both medication-based and surgical gender-affirming care for minors, and is among states that restrict this care for incarcerated people.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Montana",
    note: "Montana has passed laws restricting gender-affirming care, but unlike most restrictive states, these have reportedly been repeatedly blocked in court - actual access may differ from what the law states on paper.",
    sourceUrl: "https://williamsinstitute.law.ucla.edu/publications/bans-trans-youth-health-care/",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Wyoming",
    note: "Wyoming is reported to ban both medication-based and surgical gender-affirming care for minors.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Indiana",
    note: "Indiana's 2023 ban included a clause barring doctors from referring patients out of state for care, but a federal court has since blocked enforcement with a preliminary injunction. Current status is unclear.",
    sourceUrl: "https://www.aclu.org/press-releases/federal-court-blocks-indiana-ban-on-gender-affirming-care-for-trans-youth",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Iowa",
    note: "Iowa bans gender-affirming care (hormones, puberty blockers, and surgery) for minors.",
    sourceUrl: "https://www.findlaw.com/lgbtq-law/state-laws-on-gender-affirming-care.html",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Kansas",
    note: "Kansas's 2025 'Help Not Harm' Act bans gender-affirming care for minors, restricts public funding and referrals, and makes providing this care to minors a crime.",
    sourceUrl: "https://www.findlaw.com/lgbtq-law/state-laws-on-gender-affirming-care.html",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Oklahoma",
    note: "Oklahoma makes providing gender-affirming care to minors a felony. A newer law (SB904) also bars Medicaid and public facilities from providing or reimbursing this care for both youth and adults.",
    sourceUrl: "https://hrasantafe.org/hras-board-presidents-advocacy-brief-oklahoma-enacts-sweeping-ban-on-publicly-funded-gender-affirming-care-june-6-2026/",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "West Virginia",
    note: "West Virginia's SB299 (June 2025) banned the remaining forms of gender-affirming care for youth. The state is also reported to be expanding Medicaid restrictions for adults.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "North Dakota",
    note: "North Dakota bans gender-affirming care for minors and makes providing it a crime - a misdemeanor for hormones or puberty blockers, a felony for surgical care.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "Nebraska",
    note: "Nebraska bans gender-affirming care, including surgery, puberty blockers, and hormones, for patients under 19, and bars doctors from referring patients out of state for this care.",
    sourceUrl: "https://www.hrc.org/resources/alert-transgender-healthcare",
    lastReviewedAt: "2026-07-17",
  },
  {
    country: "United States",
    subregion: "South Dakota",
    note: "South Dakota is reported among states restricting gender-affirming care. Specific details were limited in this research pass.",
    sourceUrl: "https://worldpopulationreview.com/state-rankings/transgender-care-ban-states",
    lastReviewedAt: "2026-07-17",
  },
];

// Pure filtering/sorting, given whatever resource list the caller has on
// hand (live from Dexie's cache via useLiveQuery, or the bundled fallback
// directly - see syncRegionResourcesCache for how the cache gets filled).
export function resourcesForRegion(
  resources: RegionResource[],
  country: string | null,
  subregion: string | null
): RegionResource[] {
  if (!country) return [];
  return resources
    .filter((r) => r.country === country && (r.subregion === null || r.subregion === subregion))
    .sort((a, b) => CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category));
}

export function legalContextFor(
  notes: LegalContextNote[],
  country: string | null,
  subregion: string | null
): LegalContextNote | null {
  if (!country || !subregion) return null;
  return notes.find((n) => n.country === country && n.subregion === subregion) ?? null;
}

export const CATEGORY_LABELS: Record<ResourceCategory, string> = {
  emergency: "Emergency",
  crisis: "Crisis support",
  peer: "Peer & community",
  legal: "Legal",
  housing: "Housing",
  general: "General information",
};

function legalNoteId(country: string, subregion: string): string {
  return `${country}|${subregion}`;
}

type RegionResourceRow = {
  id: string;
  country: string;
  subregion: string | null;
  city_name: string | null;
  org_name: string;
  category: ResourceCategory;
  contact_info: string;
  availability: string | null;
  source_url: string;
  note: string | null;
  last_reviewed_at: string;
};

type LegalContextNoteRow = {
  country: string;
  subregion: string;
  note: string;
  source_url: string;
  last_reviewed_at: string;
};

function fromResourceRow(row: RegionResourceRow): CachedRegionResourceInput {
  return {
    id: row.id,
    country: row.country,
    subregion: row.subregion,
    cityName: row.city_name,
    orgName: row.org_name,
    category: row.category,
    contactInfo: row.contact_info,
    availability: row.availability,
    sourceUrl: row.source_url,
    note: row.note,
    lastReviewedAt: row.last_reviewed_at,
  };
}

function fromLegalNoteRow(row: LegalContextNoteRow): CachedLegalContextNoteInput {
  return {
    id: legalNoteId(row.country, row.subregion),
    country: row.country,
    subregion: row.subregion,
    note: row.note,
    sourceUrl: row.source_url,
    lastReviewedAt: row.last_reviewed_at,
  };
}

type CachedRegionResourceInput = RegionResource;
type CachedLegalContextNoteInput = LegalContextNote & { id: string };

// Called on every app load (see (main)/layout.tsx). Seeds the local cache
// from the bundled fallback the first time a device ever opens Blossom (so
// there's always something to show immediately, even offline), then tries a
// live fetch from Supabase to replace it with whatever staff have published
// - resources are public data, so this works with no account and no sign-in.
export async function syncRegionResourcesCache(): Promise<void> {
  const cachedCount = await db.cachedRegionResources.count();
  if (cachedCount === 0) {
    await db.cachedRegionResources.bulkPut(FALLBACK_REGION_RESOURCES);
    await db.cachedLegalContextNotes.bulkPut(
      FALLBACK_LEGAL_CONTEXT_NOTES.map((n) => ({ ...n, id: legalNoteId(n.country, n.subregion) }))
    );
  }

  try {
    const supabase = createClient();
    const [resourcesRes, notesRes] = await Promise.all([
      supabase.from("region_resources").select("*"),
      supabase.from("legal_context_notes").select("*"),
    ]);
    if (resourcesRes.error || notesRes.error || !resourcesRes.data || !notesRes.data) return;

    const resources = resourcesRes.data.map((row) => fromResourceRow(row as RegionResourceRow));
    const notes = notesRes.data.map((row) => fromLegalNoteRow(row as LegalContextNoteRow));

    await db.transaction("rw", db.cachedRegionResources, db.cachedLegalContextNotes, async () => {
      await db.cachedRegionResources.clear();
      await db.cachedRegionResources.bulkPut(resources);
      await db.cachedLegalContextNotes.clear();
      await db.cachedLegalContextNotes.bulkPut(notes);
    });
  } catch {
    // Offline or the request failed - the cache (fallback or last-fetched)
    // stays as-is, which is the right behavior rather than clearing it.
  }
}
